app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: 蓝快加速器
publisher_url: https://github.com/hiddify/hiddify-next
display_name: 蓝快加速器
executable_name: lankuai.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\lankuai"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
  - zh-cn
